config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resource :forecast, only: [:show]

  # Defines the root path route ("/")
  root "forecasts#show"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  after_action -> { flash.clear }

  def show
    q = search_params[:q]
    render and return unless q

    forecasts = fetch_forecast_info(q) do
      flash[:notice] = "Result was pulled from the cache."
    end
    if forecasts
      render locals: { forecasts:, q: }
    else
      flash[:alert] = "No results found"
    end
  end

  private

  def search_params
    params.permit(:q)
  end

  def fetch_forecast_info(q)
    cache_key = "forecast/#{q.parameterize.underscore}"
    if forecasts = Rails.cache.read(cache_key)
      yield
    else
      forecasts = Rails.cache.fetch(cache_key, expires_in: 30.minutes) do
        api_key = Rails.application.credentials.openweathermap.api_key
        Forecast.new(api_key).call(q)
      end
    end
    forecasts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def utc_to_specific(time_str, zone)
    time_str ? time_str.in_time_zone("UTC").in_time_zone(zone) : nil
  end
end

app/views/forecasts/_search.html.erb
<%= form_with(url: forecast_path, method: :get) do |form| %>
  <div class="container input-group mb-3">
    <label for="forecast_search" class="input-group-text">USA Forecast:</label>
    <input type="search" class="form-control" id="forecast_search" name="q" value="<%= q %>" placeholder="Enter zip code or city name or city name, state code">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
<% end %>

app/views/forecasts/show.html.erb
<%= render "search", q: local_assigns[:q] ? q : '' %>

<% flash.each do |_, message| %>
  <div class="alert alert-info text-center" role="alert">
    <%= message %>
  </div>
<% end %>

<% if local_assigns[:forecasts] %>
<table class="table caption-top">
  <caption class="text-center"><%= forecasts["current"]["name"] %></caption>
  <thead>
    <tr>
      <th scope="col">Time</th>
      <th scope="col">Temperature (Fahrenheit)</th>
      <th scope="col">Feels Like</th>
      <th scope="col">Min / Max</th>
      <th scope="col">Description</th>
    </tr>
  </thead>
  <tbody>
  <% [forecasts["current"], forecasts["third_hourly"]["list"]].flatten.each do |forecast|%>
    <tr>
      <th scope="row"><%= utc_to_specific(forecast["dt_txt"], forecasts["current"]["timezone"]) || "Current" %></th>
      <td><%= forecast["main"]["temp"] %></td>
      <td><%= forecast["main"]["feels_like"] %></td>
      <td><%= "#{forecast["main"]["temp_min"]} / #{forecast["main"]["temp_max"]}" %></td>
      <td><%= "#{forecast["weather"][0]["main"]} / #{forecast["weather"][0]["description"]}" %></td>
    </tr>
  </tbody>
  <% end %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherForecast</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>